Repository imdhemy/laravel-in-app-purchases, pull requests merged in 2023-01, with the labels that each got.

#238 Allow container to resolve command dependencies via handle()
  src/Console/LiapUrlCommand.php
  src/Console/RequestTestNotificationCommand.php
  tests/Doubles/LiapTestProvider.php
  tests/Handlers/AbstractNotificationHandlerTest.php
Labels: Changes requested, Fix

#246 [2.x] Bump dependencies
  composer.lock
  phpunit.xml
  src/Services/AppStoreTestNotificationServiceBuilder.php
Labels: dependencies

#251 [1.x] Improve test doubles
  phpunit.xml
  src/Services/AppStoreTestNotificationServiceBuilder.php
  tests/Console/ArtisanCommandsTest.php
  tests/Console/LiapUrlCommandTest.php
  tests/Console/RequestTestNotificationCommandTest.php
  tests/Doubles/AppStoreTestNotificationServiceBuilder.php
  tests/Doubles/LiapTestProvider.php
  tests/Doubles/UrlGenerator.php
  tests/Doubles/fixtures/appstore-server-notification.json
  tests/Doubles/fixtures/google-app-credentials.json
  tests/Doubles/fixtures/iOS-receipt.json
  tests/Doubles/fixtures/product-receipt.json
  tests/Doubles/fixtures/weird-token-from-google.json
  tests/Doubles/fixtures/x5c-chain.json
  tests/Events/AppStore/EventFactoryTest.php
  tests/Facades/ProductTest.php
  tests/Facades/SubscriptionTest.php
  tests/Faker.php
  tests/Http/Controllers/ServerNotificationControllerTest.php
  tests/ServerNotifications/AppStoreServerNotificationTest.php
  tests/TestCase.php
Labels: CI

#262 [1.x] Fetch google credentials file from the base path
  config/liap.php
  src/ServiceProviders/LiapServiceProvider.php
Labels: Fix

#265 [1.x] Improve console tests
  tests/Console/ArtisanCommandsTest.php
  tests/Console/LiapUrlCommandTest.php
Labels: CI

#267 [1.x] Get provider from server notification
  src/Contracts/ServerNotificationContract.php
  src/ServerNotifications/AppStoreServerNotification.php
  src/ServerNotifications/AppStoreV2ServerNotification.php
  src/ServerNotifications/GoogleServerNotification.php
  tests/ServerNotifications/AppStoreServerNotificationTest.php
  tests/ServerNotifications/AppStoreV2ServerNotificationTest.php
  tests/ServerNotifications/GoogleServerNotificationTest.php
Labels: Feature

#270 [1.x] Stop setting Credentials path twice
  src/ServiceProviders/LiapServiceProvider.php
Labels: Fix

#268 [1.x] Single event factory
  UPGRADE-2.0.md
  src/Contracts/EventFactory.php
  src/Events/AppStore/EventFactory.php
  src/Events/EventFactory.php
  src/Events/GooglePlay/EventFactory.php
  src/Handlers/AbstractNotificationHandler.php
  src/Handlers/AppStoreNotificationHandler.php
  src/Handlers/AppStoreV2NotificationHandler.php
  src/Handlers/GooglePlayNotificationHandler.php
  src/Handlers/HandlerHelpers.php
  src/Handlers/HandlerHelpersInterface.php
  src/ServiceProviders/LiapServiceProvider.php
  tests/Events/AppStore/EventFactoryTest.php
  tests/Events/EventFactoryTest.php
  tests/Events/GooglePlay/.gitignore
  tests/Events/GooglePlay/EventFactoryTest.php
  tests/Handlers/AbstractNotificationHandlerTest.php
Labels: Feature
